import React, { useEffect, useState } from 'react';
import { Bell, KeyRound, Palette, Save, ShieldCheck, UserRound } from 'lucide-react';
import { api } from '../api';

export default function Settings({ user }) {
  const [tab, setTab] = useState('Profile');
  const [settings, setSettings] = useState({});
  const [saved, setSaved] = useState(false);
  useEffect(() => { api.getSettings().then(setSettings).catch(()=>{}); }, []);
  const save = async () => { try { await api.updateSettings(settings); setSaved(true); setTimeout(()=>setSaved(false),1800); } catch { alert('Unable to save settings'); } };
  const profile = user?.name || 'Administrator';
  return <div className="editorial-page">
    <div className="page-head"><div><div className="page-kicker">Workspace preferences</div><h1 className="page-title">Settings.</h1><p className="page-intro">Keep identity, notifications, appearance, and AI configuration in one restrained workspace.</p></div><button className="primary-btn" onClick={save}><Save size={14}/> {saved?'Saved':'Save changes'}</button></div>
    <div style={{display:'grid',gridTemplateColumns:'180px 1fr',gap:16}}>
      <nav className="paper-card card-padding" style={{height:'fit-content',display:'grid',gap:5}}>{[['Profile',UserRound],['Security',ShieldCheck],['Notifications',Bell],['Appearance',Palette],['AI Configuration',KeyRound]].map(([label,Icon])=><button key={label} className={`tab-btn ${tab===label?'active':''}`} style={{textAlign:'left'}} onClick={()=>setTab(label)}><Icon size={14}/>&nbsp; {label}</button>)}</nav>
      <section className="paper-card card-padding">
        {tab==='Profile' && <><div className="page-kicker">Profile</div><h2 className="card-title" style={{marginTop:7}}>Profile information</h2><div className="field-grid" style={{marginTop:18}}><label className="field-item"><span className="field-key">Full name</span><input className="editorial-input" style={{marginTop:7}} value={profile} readOnly/></label><label className="field-item"><span className="field-key">Email</span><input className="editorial-input" style={{marginTop:7}} value={user?.email || 'demo@deepflow.ai'} readOnly/></label><label className="field-item"><span className="field-key">Role</span><input className="editorial-input" style={{marginTop:7}} value={user?.role || 'Admin'} readOnly/></label><label className="field-item"><span className="field-key">Department</span><input className="editorial-input" style={{marginTop:7}} value="Finance" onChange={()=>{}}/></label></div></>}
        {tab==='Security' && <><div className="page-kicker">Security</div><h2 className="card-title" style={{marginTop:7}}>Access and session</h2><div style={{marginTop:18,display:'grid',gap:12}}><div className="workflow-item"><div className="workflow-icon"><ShieldCheck size={16}/></div><div><strong>API session</strong><div className="card-subtitle">Backend access is routed through the FastAPI service.</div></div><span className="pill pill-approved">Active</span></div><div className="workflow-item"><div className="workflow-icon"><KeyRound size={16}/></div><div><strong>Service credentials</strong><div className="card-subtitle">Firebase server credentials stay on the Render backend.</div></div><span className="pill pill-low">Protected</span></div></div></>}
        {tab==='Notifications' && <><div className="page-kicker">Notifications</div><h2 className="card-title" style={{marginTop:7}}>Attention settings</h2><div style={{marginTop:18,display:'grid',gap:12}}>{['High-risk document alerts','Workflow approval reminders','Daily activity summary'].map(item=><label key={item} className="workflow-item"><div className="workflow-icon"><Bell size={15}/></div><span style={{fontSize:11,fontWeight:700}}>{item}</span><input type="checkbox" defaultChecked style={{marginLeft:'auto',accentColor:'#214b3a'}}/></label>)}</div></>}
        {tab==='Appearance' && <><div className="page-kicker">Appearance</div><h2 className="card-title" style={{marginTop:7}}>Ivory Editorial</h2><p className="page-intro">DeepFlow is intentionally presented as a calm, paper-led interface with forest accents and serif display typography.</p><div className="paper-card" style={{marginTop:18,padding:18,background:'#18241f',color:'#fffdf8'}}><div className="page-kicker" style={{color:'#d4b875'}}>Design language</div><div style={{font:'600 34px/1.05 Playfair Display, Georgia, serif',marginTop:8}}>Quiet software.<br/>Clear decisions.</div></div></>}
        {tab==='AI Configuration' && <><div className="page-kicker">AI configuration</div><h2 className="card-title" style={{marginTop:7}}>Decision model</h2><div style={{marginTop:18,display:'grid',gap:12}}><div className="field-item"><span className="field-key">Provider</span><div style={{marginTop:5,fontWeight:700,fontSize:11}}>Demo / configured backend AI</div></div><div className="field-item"><span className="field-key">Document grounding</span><div style={{marginTop:5,fontWeight:700,fontSize:11}}>Enabled for document Q&A</div></div><div className="field-item"><span className="field-key">Output handling</span><div style={{marginTop:5,fontWeight:700,fontSize:11}}>Stored alongside Firestore analysis records</div></div></div></>}
      </section>
    </div>
  </div>;
}
